Add step to fail build

diff --git a/.github/workflows/shared-scan-container.yml b/.github/workflows/shared-scan-container.yml
--- a/.github/workflows/shared-scan-container.yml
+++ b/.github/workflows/shared-scan-container.yml
@@ -102,7 +102,7 @@ jobs:
 
       - name: Comment on Scan Failure
         id: comment_on_scan_failure
-        if: failure() && steps.scan.outcome == 'failure'
+        if: steps.scan.outcome == 'failure'
         uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
         with:
           script: |
@@ -112,3 +112,10 @@ jobs:
               repo: context.repo.repo,
               body: 'Container scan has failed, please refer to the [User Guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/services/airflow/index.html#vulnerability-scanning) for more information.'
             })
+
+      - name: Fail on Scan Failure
+        id: fail_on_scan_failure
+        if: steps.scan.outcome == 'failure'
+        run: |
+          echo "steps.scan.outcome == 'failure', exiting."
+          exit 1
